name: CI

on:
  push:
    branches: [ main, develop, 'feat/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  data-validation:
    runs-on: ubuntu-latest
    name: Data Validation
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Run CSV Validation
      run: npm run data:lint

  build:
    runs-on: ubuntu-latest
    needs: data-validation
    name: Build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install --if-present
    
    - name: Build
      run: npm run build --if-present
    
    - name: Test
      run: npm test --if-present
